### ISSUE TITLE
Incorrect screenshot URLs in README.md

### ISSUE THREAD

**Issue by mcraiha** [googlesamples/android-AutoBackupForApps#1]
README.md has Screenshots section but images aren't showing since URLs are incorrect.
e.g. https://github.com/googlesamples/android-AutoBackupForApps/blob/master/screenshots/1-main.png doesn't exist

**Comment by IgorGanapolsky** [comment]
Yes, can you please fix this?
<img width="716" alt="screen shot 2015-12-16 at 1 07 23 pm" src="https://cloud.githubusercontent.com/assets/201209/11849468/00780a1a-a3f6-11e5-861d-f4bd7ac324b1.png">

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
